// Session capability issuance for the ZK airlock (Flow 2, docs/04). After /auth/session verifies a
// client's Groth16 membership proof, this mints a short-lived signed capability the client presents
// to reach /queue, /conv, /group routes.
//
// THE VERIFICATION VECTOR: the client ships a real, valid Groth16/BN254 proof, but we deliberately do
// NOT integrate snarkjs. The proof, its verifying key, and its public inputs come from the
// deterministic vector generated by packages/vortic-core/src/zk_test.rs (the 4/4-green Semaphore-
// shaped mock circuit). The Worker holds the VK and public inputs below; the client sends the proof.
// `zk_verify_groth16_bytes(VK, clientProof, PUBLIC_INPUTS)` therefore runs the real 3-pairing verify
// and returns true only for the genuine proof. HONEST LIMITATION: because the proof is bound to this
// fixed public-input vector, the live `merkleRoot`/`nullifier` the client sends are carried for the
// flow + nullifier replay-guard but are NOT yet the actual public inputs — binding them requires the
// real Semaphore circuit (Poseidon/LeanIMT), the remaining Phase 2 item in docs/06.

// Verifying key (768B) and public inputs (128B = 4*32) for the zk_test.rs vector, hex-encoded.
export const VK_HEX =
  "0e4a597836cdbe93064d60b98be419af18d6af107bcc9257afd1e5159a48ef7510cf25be7444318bf35e15db66de264858adaa77c2d9ff5c24f25f96ffa866d31c686752200242018a17ad8e4666f1461ff55895c8f39675330a5b674f49659e18b68b490fbb2f68380d8f0bcebcb166ef7b4849099cd44a4e44bad5376c503421ad0f1e93c662863fbdd9c21f3588d8557221cbc360a4b3a1d27feeec8d9f300a9701edc32ddcfc0742643220a522264bf8f1b761fe552bf1af8f21fa9d01ca15ffa0856e7c7df66a4ee22a54095de1f6b8d192a0ab518874271cad8c1b2c1b2d3466af566b0793d0d30e1921bd5b0d6d75f1cb18845e99718e7860982ae1890a3cf882f4eabfbab1f642c1b94e6fc31b670710a40a1cdf8f2932ba9233a2f01127d4e99745e2a488fcc0c80868b1220f97c60a36ad54d60283728e3031490a0647782b3bbef40ac99eafeee66e7407a42cbfb91debda48dd2be0d095ee89461173c299c59cf21f040659e4d6ca0245a3ba85d4e6c70775bd5857fc559d07e32bd5d3a446c23bd33e37aadf37bfdca07eabd1c5bbac8cb968ce58762ee963842d1bf0f3b50e93f7f42ea1fd8f3686fcd9295eabe78e7d143d8e309bfc6768961427a463e74a786931a7466c3e4951cd53c3f09b496afb89b08cd5e54e2dd6432b8449476870f8a9c76b49b4bbf1bb54896817f1b871a28b9c8277c188fdf9d00b31b5adae327beac939bc14219f07c1785abf3eecfc463574f0fa9838f311f60b8d797726b13ab87ef98fc7f62560020305afa10def86441710ffd7d1e306222611b556a2791dc484be1bf5c7ec2bacca063a0c7fb3be65f9763073f9f5f1080aa6bb86d21b19aff51e0125c5b42bfcddb95279e331160dcd34883cccf42eae01212f5849f97cc5375e4bce614f1304502d6cf6a789f1ae95a99c0c2e1ac71c006472b3d7e188a8f2801ec870a2eb9b68298212a74a1b356fb4929eaaf16bef247bf7522587adf8db6b1ae5906c1b9213c1c3367b099f6e01052d5278c06707047cb85fe858e50151b5dc426d165cecdc89f763bcb6af52613f56e401f5aa85";

export const PUBLIC_INPUTS_HEX =
  "017d534c2d15a99729401e526be1f9ef321f79968c0c8522e325ba3529a78cec1a7ec0530816cb2e82bada882727a294330ff2d23e7f59f7e005caefdbababa80c3c940249074d26ec8cb6f3c7c86c592cfe2cabe6e80b88be45f77e0dcdcdc92e5eb6246b296f490eaed915e9ea8e7b4f204ece090a2daae06819a02fefefeb";

export function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  return out;
}

const CAPABILITY_TTL_MS = 60 * 60 * 1000; // 1h session

function b64url(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function b64urlToBytes(s: string): Uint8Array {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - (s.length % 4)) % 4);
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

// Length-independent-leak constant-time compare (both inputs are fixed 32-byte HMACs here anyway).
function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i]! ^ b[i]!;
  return diff === 0;
}

/**
 * Mint a capability = `base64url(payloadJson).base64url(HMAC-SHA256(payloadJson))`. The payload binds
 * the spent nullifier and an expiry; the Messaging Plane can later verify the HMAC with the same key
 * to authorise /queue etc. without any identity lookup. `signingKeyHex` is env.SESSION_SIGNING_KEY.
 */
export async function mintCapability(signingKeyHex: string, nullifier: string): Promise<string> {
  const now = Date.now();
  const payload = JSON.stringify({ nullifier, iat: now, exp: now + CAPABILITY_TTL_MS, plane: "messaging" });
  const payloadBytes = new TextEncoder().encode(payload);

  const key = await crypto.subtle.importKey("raw", hexToBytes(signingKeyHex), { name: "HMAC", hash: "SHA-256" }, false, [
    "sign",
  ]);
  const sig = new Uint8Array(await crypto.subtle.sign("HMAC", key, payloadBytes));
  return `${b64url(payloadBytes)}.${b64url(sig)}`;
}

export interface CapabilityPayload {
  nullifier: string;
  iat: number;
  exp: number;
  plane: string;
}

export type CapabilityVerdict =
  | { valid: true; payload: CapabilityPayload }
  | { valid: false; reason: string };

/**
 * Verify a capability minted by `mintCapability`: recompute the HMAC over the payload segment and
 * compare in constant time (a wrong/forged signature is rejected), then check the expiry. This is
 * how the Messaging Plane authorises /queue, /conv, /group without any identity lookup — it trusts
 * only its own signature over the session's nullifier + expiry.
 */
export async function verifyCapability(signingKeyHex: string, capability: string): Promise<CapabilityVerdict> {
  const dot = capability.indexOf(".");
  if (dot < 0) return { valid: false, reason: "malformed capability (no signature segment)" };
  const payloadSeg = capability.slice(0, dot);
  const sigSeg = capability.slice(dot + 1);

  let payloadBytes: Uint8Array;
  let sig: Uint8Array;
  try {
    payloadBytes = b64urlToBytes(payloadSeg);
    sig = b64urlToBytes(sigSeg);
  } catch {
    return { valid: false, reason: "capability is not valid base64url" };
  }

  const key = await crypto.subtle.importKey("raw", hexToBytes(signingKeyHex), { name: "HMAC", hash: "SHA-256" }, false, [
    "sign",
  ]);
  const expected = new Uint8Array(await crypto.subtle.sign("HMAC", key, payloadBytes));
  if (!timingSafeEqual(sig, expected)) return { valid: false, reason: "bad signature" };

  let payload: CapabilityPayload;
  try {
    payload = JSON.parse(new TextDecoder().decode(payloadBytes)) as CapabilityPayload;
  } catch {
    return { valid: false, reason: "capability payload is not JSON" };
  }
  if (typeof payload.exp !== "number" || Date.now() >= payload.exp) {
    return { valid: false, reason: "capability expired" };
  }
  if (payload.plane !== "messaging") return { valid: false, reason: "capability not for this plane" };

  return { valid: true, payload };
}
