// Public @alias registration widget (docs/03 §8) — "alias contact establishment" pass (2026-07).
// Self-contained like SecureScorePanel: owns its own load/register state, embeddable with no
// page-level logic of its own. No update/revoke UI — `AliasDO.ts` doesn't support either yet (see
// its own header comment), so once registered this becomes read-only for the nickname itself.
//
// Device-linking added (2026-07, requested live: "between devices, doesn't @alias sync? if not, it
// should") — registration used to be purely per-device, with no way for a second device to present
// the same identity. See lib/alias.ts's own header comment on the linking section for the design
// (reuses DeviceLinkDO's existing one-time dead-drop, no backend changes).
import { useEffect, useState } from "react";
import { AtSign, Copy, Laptop, Loader2 } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../contexts/ToastContext";
import {
  buildAliasLinkUrl,
  claimAliasLink,
  clearAliasLinkHash,
  generateAliasLinkingSecret,
  isValidNickname,
  loadOwnAlias,
  parseAliasLinkFromLocation,
  publishAliasLink,
  registerAlias,
  type OwnAlias,
} from "../lib/alias";

export function AliasPanel() {
  const { token: cap } = useAuth();
  const { showToast } = useToast();
  const [own, setOwn] = useState<OwnAlias | null | "loading">("loading");
  const [draft, setDraft] = useState("");
  const [mining, setMining] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [linking, setLinking] = useState(false);
  const [linkUrl, setLinkUrl] = useState<string | null>(null);
  const [claiming, setClaiming] = useState(false);

  useEffect(() => {
    let cancelled = false;
    loadOwnAlias().then((result) => {
      if (!cancelled) setOwn(result);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  // Claiming side: open a `#/alias-link/<code>` link generated by ANOTHER of your own devices ->
  // pulls that device's alias identity and adopts it here, overwriting anything already registered
  // locally (same "whoever holds the code wins" trust model as lib/deviceLink.ts's chat linking).
  useEffect(() => {
    if (!cap) return;
    const secret = parseAliasLinkFromLocation();
    if (!secret) return;
    clearAliasLinkHash();
    setClaiming(true);
    (async () => {
      try {
        const claimed = await claimAliasLink(secret, cap);
        if (claimed) {
          setOwn(claimed);
          showToast(`Linked @${claimed.nickname} to this device`, "success");
        } else {
          showToast("This link is invalid, already claimed, or expired", "error");
        }
      } catch (err) {
        showToast(`Failed to link alias: ${(err as Error).message}`, "error");
      } finally {
        setClaiming(false);
      }
    })();
  }, [cap, showToast]);

  const submit = async () => {
    if (!cap || mining) return;
    const nickname = draft.trim().toLowerCase();
    if (!isValidNickname(nickname)) {
      setError("3-32 characters, lowercase letters/digits/underscore only");
      return;
    }
    setError(null);
    setMining(true);
    try {
      const result = await registerAlias(nickname, cap);
      setOwn(result);
    } catch (err) {
      setError((err as Error).message.includes("409") ? "That nickname is already taken" : (err as Error).message);
    } finally {
      setMining(false);
    }
  };

  const handleLinkToDevice = async () => {
    if (!cap || linking) return;
    setLinking(true);
    try {
      const secret = generateAliasLinkingSecret();
      await publishAliasLink(secret, cap);
      const url = buildAliasLinkUrl(secret);
      setLinkUrl(url);
      navigator.clipboard
        ?.writeText(url)
        .then(() => showToast("Link copied to clipboard", "success"))
        .catch(() => {});
    } catch (err) {
      showToast(`Failed to create a link: ${(err as Error).message}`, "error");
    } finally {
      setLinking(false);
    }
  };

  return (
    <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
      <div className="flex items-center gap-2 mb-1">
        <AtSign className="w-4 h-4 text-fluid-peach" />
        <h3 className="text-sm font-semibold text-white">Public Alias</h3>
      </div>
      <p className="text-xs text-white/50 mb-4">
        Opt-in discoverability. The server learns only <span className="text-white/70">@nickname → an intro queue</span> — never your
        real identity. Off by default; once registered, this cannot be changed yet.
      </p>

      {claiming && (
        <div className="flex items-center gap-2 text-xs text-white/50 mb-3">
          <Loader2 className="w-3.5 h-3.5 animate-spin" /> Linking alias from your other device...
        </div>
      )}

      {own === "loading" && <div className="text-xs text-white/40">Loading...</div>}

      {own !== "loading" && own !== null && (
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2 text-sm text-white">
            <span className="text-fluid-peach font-mono">@{own.nickname}</span>
            <span className="text-white/40 text-xs">registered on this device</span>
          </div>
          {!linkUrl ? (
            <button
              type="button"
              onClick={() => void handleLinkToDevice()}
              disabled={linking || !cap}
              className="self-start flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg bg-white/5 hover:bg-white/10 text-white/70 transition-colors disabled:opacity-50"
            >
              {linking ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Laptop className="w-3.5 h-3.5" />}
              Link this alias to another device
            </button>
          ) : (
            <div className="flex items-center gap-2 rounded-lg border border-fluid-peach/30 bg-fluid-peach/10 px-3 py-2">
              <span className="text-[11px] text-white/70 shrink-0">Copied — open on your other device:</span>
              <input
                readOnly
                value={linkUrl}
                onFocus={(e) => e.currentTarget.select()}
                className="flex-1 min-w-0 bg-black/30 border border-white/10 rounded px-2 py-1 text-[11px] text-white/90 font-mono"
              />
              <button
                type="button"
                onClick={() => navigator.clipboard?.writeText(linkUrl).catch(() => {})}
                className="shrink-0 p-1 rounded text-white/40 hover:text-white transition-colors"
              >
                <Copy className="w-3.5 h-3.5" />
              </button>
            </div>
          )}
        </div>
      )}

      {own === null && (
        <div className="flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <input
              type="text"
              placeholder="nickname"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && void submit()}
              disabled={mining}
              maxLength={32}
              className="flex-1 min-w-0 bg-black/30 border border-white/10 rounded-lg py-2 px-3 text-sm text-white placeholder-white/40 focus:outline-none focus:border-fluid-peach/50 disabled:opacity-50"
            />
            <button
              type="button"
              onClick={() => void submit()}
              disabled={mining || !cap}
              className="shrink-0 px-4 py-2 text-xs rounded-lg bg-fluid-peach/90 hover:bg-fluid-peach text-black transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
            >
              {mining && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
              {mining ? "Mining proof-of-work..." : "Register"}
            </button>
          </div>
          {mining && <p className="text-[11px] text-white/40">This proves real computational cost to the server (anti-spam) — usually a few seconds.</p>}
          {error && <p className="text-[11px] text-signal-danger">{error}</p>}
          <p className="text-[11px] text-white/30">Already registered on another of your own devices? Open the link it gives you there instead of registering again.</p>
        </div>
      )}
    </div>
  );
}
