name = "vorticity-backend"
main = "src/index.js"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "xfeatures-vorticity"
database_id = "735a4c99-bc4e-4baa-938a-d13908985315"

[[r2_buckets]]
binding = 'IMAGES_BUCKET'
bucket_name = 'vorticity-images'

[vars]
IDM_URL = "https://account.xfeatures.net"
OAUTH_CLIENT_ID = "xf_9116480c21a94a849a1182717e35f335"
