// Split-view messenger UI (Phase 4, real contacts as of 2026-07). Real interactive state, not
// static mockup: selecting a chat clears its unread badge, and sending a message appends it to that
// conversation AND updates the list's preview/timestamp — both driven from one `chats` array here,
// not two disconnected pieces of state. The chat LIST itself is real now (lib/chatList.ts, built from
// actually-created/-joined invites, not a hardcoded mock array), and as of 2026-07 that same module
// ALSO persists message history locally (sealed via lib/secureStore.ts, same non-extractable vault
// `useQueueTransport.ts`'s identity material uses) — navigating away and back, or a reload, no longer
// wipes a visible conversation on THIS device. See lib/chatList.ts's header comment for the honest
// scope: this is local-device-only, not real multi-device sync — that still needs `ConvLogDO`'s
// op-log wired in here, separate, not-yet-built work per docs/06 Phase 3.
import { useCallback, useEffect, useRef, useState } from "react";
import { ChatList } from "../components/chat/ChatList";
import { ActiveChatPanel } from "../components/chat/ActiveChatPanel";
import { useQueueTransport } from "../hooks/useQueueTransport";
import { usePresence } from "../hooks/usePresence";
import { useAuth } from "../contexts/AuthContext";
import { formatNow, type Chat, type ChatMessage } from "../lib/chat";
import { loadChatList, saveChatList } from "../lib/chatList";
import { clearFromStore } from "../lib/secureStore";
import {
  buildInviteUrl,
  clearInviteHash,
  generateInviteChatId,
  parseInviteFromLocation,
  takeStashedPendingInvite,
} from "../lib/inviteLink";
import {
  applyLinkPayload,
  buildLinkPayload,
  buildLinkUrl,
  generateLinkingSecret,
  parseLinkCodeFromLocation,
  putLinkPayload,
  takeLinkPayload,
} from "../lib/deviceLink";

export function Chats() {
  const { token: cap } = useAuth();
  const [chats, setChats] = useState<Chat[]>([]);
  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const [pendingInvite, setPendingInvite] = useState<{ chatId: string; url: string } | null>(null);
  const [pendingDeviceLink, setPendingDeviceLink] = useState<{ chatId: string; url: string } | null>(null);
  // Gates the persist-on-change effect below until the initial restore has actually run — otherwise
  // the very first render's empty `chats` would get saved and clobber whatever was in the vault
  // before the restore even finishes loading it back.
  const hasRestoredRef = useRef(false);

  const activeChat = chats.find((c) => c.id === activeChatId) ?? null;

  // Restore the persisted chat list, THEN (not in a separate/racing effect) merge in a pending
  // invite if one exists — sequencing matters here: a separate effect for each would race (the
  // invite-join could add a chat to the empty initial `[]`, then the restore's `setChats` would
  // overwrite it with the persisted list, silently dropping the just-joined invite).
  //
  // Checks the URL hash FIRST, then a stashed invite from sessionStorage (2026-07 fix — see
  // AuthGuard.tsx/lib/inviteLink.ts: someone opening an invite link while NOT yet authenticated gets
  // redirected through SecurityGate -> OAuth -> AuthCallback and lands back here with no hash of its
  // own; the invite survived that trip via the stash, not the URL).
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const restored = await loadChatList();
      if (cancelled) return;
      const invite = parseInviteFromLocation() ?? takeStashedPendingInvite();
      if (invite) {
        clearInviteHash();
        if (!restored.some((c) => c.id === invite.chatId)) {
          // Contact-bootstrap, joining side: someone opened a link generated by handleCreateInvite
          // below. This side always takes the OPPOSITE role from whoever generated the link
          // ("initiator": per PQXDH's one-sided handshake, useQueueTransport.ts's header comment,
          // this side verifies + encapsulates in response to the responder's signed prekey bundle,
          // which still flows over the queue itself — see lib/inviteLink.ts for why the bundle isn't
          // also embedded in the URL). `invite.label`, if the inviter set one, is a purely cosmetic
          // display name — see lib/inviteLink.ts's header comment for why it's not a public alias.
          restored.push({
            id: invite.chatId,
            alias: invite.label ? `Invited by: ${invite.label}` : "New contact",
            initials: invite.label ? invite.label.slice(0, 2).toUpperCase() : "IN",
            role: "initiator",
            online: false,
            unreadCount: 0,
            lastMessage: "Joined via invite link — waiting for handshake...",
            lastMessageAt: formatNow(),
            messages: [],
            presenceEnabled: false,
          });
        }
        setActiveChatId(invite.chatId);
      }

      // Device-linking pass: redeem a `#/device-link/<code>` hash the SAME way an invite hash is
      // read (parse-without-navigating, then clear) — see lib/deviceLink.ts's header comment for why
      // this is a materially higher-stakes secret than an invite code (full chat state, not just "may
      // start a session"). Requires `cap` (this device's own real session capability — DeviceLinkDO
      // is capability-gated, see its header comment for why linking doesn't bypass account auth).
      const linkSecret = parseLinkCodeFromLocation();
      if (linkSecret && cap) {
        clearInviteHash(); // generic hash-clear, not invite-specific despite the name — see its own doc comment
        try {
          const payload = await takeLinkPayload(linkSecret, cap);
          if (payload && !cancelled) {
            const linkedChat = await applyLinkPayload(payload);
            const existingIdx = restored.findIndex((c) => c.id === linkedChat.id);
            if (existingIdx >= 0) restored[existingIdx] = linkedChat;
            else restored.push(linkedChat);
            setActiveChatId(linkedChat.id);
            console.log(`[DeviceLink] Redeemed a device-link code for chat ${linkedChat.id.slice(0, 12)}... — history + crypto state applied.`);
          } else if (!cancelled) {
            console.warn("[DeviceLink] This code is invalid, already claimed, or expired.");
          }
        } catch (err) {
          console.warn("[DeviceLink] Failed to redeem device-link code:", (err as Error).message);
        }
      }

      setChats(restored);
      hasRestoredRef.current = true;
    })();
    return () => {
      cancelled = true;
    };
  }, [cap]);

  // Persist the list, including message history (see lib/chatList.ts), whenever it changes — fires
  // on every message too, not just on create/join, since there's no cheaper signal to distinguish "a
  // chat was added" from "a chat's messages changed" without extra bookkeeping that isn't worth it at
  // this scale (re-sealing the whole list on every message is cheap for an alpha's realistic chat/
  // message counts; revisit if that stops being true).
  useEffect(() => {
    if (!hasRestoredRef.current) return;
    saveChatList(chats).catch((err) => console.warn("[Chats] Failed to persist chat list:", (err as Error).message));
  }, [chats]);

  // Appends a message pushed down the wire for `chatId` into that chat's history. Only the active
  // chat ever has a live socket (see useQueueTransport's scoping note), so this always targets the
  // conversation currently on screen — no unread-badge bump needed, it's already being read live.
  const handleIncoming = useCallback((chatId: string, message: ChatMessage) => {
    setChats((prev) =>
      prev.map((c) =>
        c.id === chatId
          ? { ...c, messages: [...c.messages, message], lastMessage: message.text, lastMessageAt: message.timestamp }
          : c,
      ),
    );
  }, []);

  // Per-chat role now (was a hardcoded "initiator" for every chat): the 4 mock contacts keep
  // defaulting to "initiator" (mockChats.ts), while invite-bootstrapped chats carry whichever role
  // they were actually assigned above / in handleCreateInvite below — a real two-party exchange needs
  // one side on each role, per PQXDH's one-sided handshake (useQueueTransport.ts's header comment).
  const { status: socketStatus, sendMessage, hasLease, leaseHeldByOther, exportRatchetState, getTrustedPeerBundle } = useQueueTransport(
    activeChatId,
    activeChat?.role ?? "initiator",
    handleIncoming,
  );

  // Opt-in presence (docs/06 "Still open: PresenceDO", closed 2026-07) — only live for the active
  // chat, only connects when that chat's own `presenceEnabled` toggle is on. See usePresence.ts's
  // header comment for why this doesn't try to track every background chat's presence too.
  const { peerOnline, peerTyping, sendTyping } = usePresence(activeChatId, activeChat?.presenceEnabled ?? false);

  const handleSelect = (id: string) => {
    setActiveChatId(id);
    setChats((prev) => prev.map((c) => (c.id === id ? { ...c, unreadCount: 0 } : c)));
    if (pendingInvite && pendingInvite.chatId !== id) setPendingInvite(null);
  };

  // Contact/chat deletion: removes the chat from the local list AND every piece of local crypto
  // state associated with it — a stale identity/prekey-pool/imported-ratchet-state record left
  // behind after "deleting" a chat would be a real residual-data leak, not just visual clutter.
  // LOCAL-DEVICE ONLY (same honest scope as the rest of lib/chatList.ts — see its header comment):
  // this does not tell the peer anything, does not reach any server-side DO (PrekeyDO/PresenceDO/
  // DeviceLeaseDO state for this chat is left to its own TTL/alarm-driven cleanup, same as it already
  // is for an abandoned chat today), and does not delete this chat on any other of the user's own
  // linked devices.
  const handleDeleteChat = async (id: string) => {
    if (!window.confirm("Delete this chat? This removes the local message history and crypto state on this device and cannot be undone.")) {
      return;
    }
    if (activeChatId === id) setActiveChatId(null);
    setChats((prev) => prev.filter((c) => c.id !== id));
    await Promise.all(
      [`ratchet-identity:${id}`, `ratchet-kem:${id}`, `ratchet-kem-rotated-at:${id}`, `ratchet-imported-state:${id}`, `onetime-pool:${id}`].map(
        (key) => clearFromStore(key).catch(() => {}),
      ),
    );
  };

  const handleTogglePresence = () => {
    if (!activeChatId) return;
    setChats((prev) => prev.map((c) => (c.id === activeChatId ? { ...c, presenceEnabled: !c.presenceEnabled } : c)));
  };

  // Live `online` for the active row only — deliberately NOT written into `chats` state itself (that
  // would re-trigger the persist-on-change effect above on every flicker, sealing the vault far more
  // often than a real preference change warrants). The list/panel render off this derived view instead.
  const displayChats = chats.map((c) => (c.id === activeChatId ? { ...c, online: peerOnline } : c));
  const displayActiveChat = displayChats.find((c) => c.id === activeChatId) ?? null;

  // Contact-bootstrap, generating side: creates a fresh unguessable chat id, adds it to the list as
  // "responder" (so useQueueTransport's existing responder-mount effect publishes a real signed
  // PQXDH prekey bundle onto that queue immediately — QueueDO's backlog-flush-on-connect means
  // whoever opens the link later still receives it, even if this tab has since closed), and surfaces
  // the shareable link (best-effort clipboard copy + a visible fallback banner, since clipboard
  // access can silently fail depending on permissions/context).
  const handleCreateInvite = (label?: string) => {
    const chatId = generateInviteChatId();
    const url = buildInviteUrl(chatId, label);
    setChats((prev) => [
      ...prev,
      {
        id: chatId,
        alias: "New contact",
        initials: "IN",
        role: "responder",
        online: false,
        unreadCount: 0,
        lastMessage: "Invite created — waiting for your contact to join...",
        lastMessageAt: formatNow(),
        messages: [],
        presenceEnabled: false,
      },
    ]);
    setActiveChatId(chatId);
    setPendingInvite({ chatId, url });
    navigator.clipboard?.writeText(url).catch(() => {});
  };

  // Device-linking pass: seals the active chat's full state (identity/KEM/pool for a responder, the
  // live ratchet session if established, and message history) and drops it at DeviceLinkDO for a
  // second device to redeem — see lib/deviceLink.ts's header comment for the sensitivity of what
  // this actually shares (move the resulting link between your OWN devices only). Only offered while
  // `hasLease` — exporting from a read-only device would hand over stale state, see
  // useQueueTransport.ts's `exportRatchetState` doc comment.
  const handleLinkDevice = async () => {
    if (!activeChat || !cap || !hasLease) return;
    try {
      const secret = generateLinkingSecret();
      const payloadBytes = await buildLinkPayload(activeChat, exportRatchetState(), getTrustedPeerBundle());
      await putLinkPayload(secret, cap, payloadBytes);
      const url = buildLinkUrl(secret);
      setPendingDeviceLink({ chatId: activeChat.id, url });
      navigator.clipboard?.writeText(url).catch(() => {});
    } catch (err) {
      console.warn("[DeviceLink] Failed to create a device-link code:", (err as Error).message);
    }
  };

  const handleSend = (text: string) => {
    if (!activeChatId) return;
    // Optimistic local echo (instant feedback, standard messaging UX) *and* a real send over the
    // wire — the mock endpoint won't echo it back, so without the local append the sent bubble
    // would never appear. This is a deliberate Phase 5 scoping call, not a leftover mock.
    const message: ChatMessage = { id: crypto.randomUUID(), senderId: "me", text, timestamp: formatNow() };
    setChats((prev) =>
      prev.map((c) =>
        c.id === activeChatId ? { ...c, messages: [...c.messages, message], lastMessage: text, lastMessageAt: message.timestamp } : c,
      ),
    );
    sendMessage(text);
  };

  const showInviteBanner = pendingInvite !== null && pendingInvite.chatId === activeChatId;
  const showDeviceLinkBanner = pendingDeviceLink !== null && pendingDeviceLink.chatId === activeChatId;

  return (
    <div className="h-full flex flex-col gap-3">
      {showInviteBanner && (
        <div className="shrink-0 flex items-center gap-3 rounded-xl border border-fluid-peach/30 bg-fluid-peach/10 px-4 py-2.5 text-sm text-white">
          <span className="text-white/70 shrink-0">Invite link (copied to clipboard):</span>
          <input
            readOnly
            value={pendingInvite!.url}
            onFocus={(e) => e.currentTarget.select()}
            className="flex-1 min-w-0 bg-black/30 border border-white/10 rounded-lg px-2 py-1 text-xs text-white/90 font-mono"
          />
          <button
            type="button"
            onClick={() => navigator.clipboard?.writeText(pendingInvite!.url).catch(() => {})}
            className="shrink-0 px-3 py-1 text-xs rounded-lg bg-fluid-peach/90 hover:bg-fluid-peach text-black transition-colors"
          >
            Copy
          </button>
          <button type="button" onClick={() => setPendingInvite(null)} className="shrink-0 text-white/40 hover:text-white text-xs px-1">
            Dismiss
          </button>
        </div>
      )}
      {showDeviceLinkBanner && (
        <div className="shrink-0 flex items-center gap-3 rounded-xl border border-signal-danger/30 bg-signal-danger/10 px-4 py-2.5 text-sm text-white">
          <span className="text-white/70 shrink-0">
            Device-link code (copied — move to your OWN other device only, valid 10 min):
          </span>
          <input
            readOnly
            value={pendingDeviceLink!.url}
            onFocus={(e) => e.currentTarget.select()}
            className="flex-1 min-w-0 bg-black/30 border border-white/10 rounded-lg px-2 py-1 text-xs text-white/90 font-mono"
          />
          <button
            type="button"
            onClick={() => navigator.clipboard?.writeText(pendingDeviceLink!.url).catch(() => {})}
            className="shrink-0 px-3 py-1 text-xs rounded-lg bg-signal-danger/90 hover:bg-signal-danger text-black transition-colors"
          >
            Copy
          </button>
          <button type="button" onClick={() => setPendingDeviceLink(null)} className="shrink-0 text-white/40 hover:text-white text-xs px-1">
            Dismiss
          </button>
        </div>
      )}
      <div className="flex-1 min-h-0 flex rounded-2xl border border-white/10 overflow-hidden vx-glass-dimmable">
        <ChatList
          chats={displayChats}
          activeChatId={activeChatId}
          onSelect={handleSelect}
          onCreateInvite={handleCreateInvite}
          onDelete={handleDeleteChat}
        />
        <ActiveChatPanel
          chat={displayActiveChat}
          socketStatus={socketStatus}
          onSend={handleSend}
          peerTyping={peerTyping}
          onTypingDraft={sendTyping}
          onTogglePresence={handleTogglePresence}
          onLinkDevice={handleLinkDevice}
          canLinkDevice={hasLease}
          leaseHeldByOther={leaseHeldByOther}
        />
      </div>
    </div>
  );
}
